# Configuração Nixpacks para Railway
# Otimizado para Laravel 11 com PHP 8.2

[phases.setup]
nixPkgs = ['php82', 'nodejs-18_x', 'npm-9_x']
nixpkgsArchive = "e9ee548d90ff586a6471b4ae80ae9cfcbceb3420"

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist',
    'npm ci --only=production --silent',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'chmod -R 755 storage bootstrap/cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
APP_ENV = 'production'
APP_DEBUG = 'false'
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'error'
DB_CONNECTION = 'mysql'
SESSION_DRIVER = 'database'
CACHE_DRIVER = 'database'
QUEUE_CONNECTION = 'database'
NIXPACKS_BUILD_CPU_LIMIT = '2'
NIXPACKS_BUILD_MEMORY_LIMIT = '4096'
NIXPACKS_NO_CACHE = 'false'