[phases.setup]
nixPkgs = ['php82', 'nodejs_18', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

[variables]
APP_ENV = 'production'
APP_DEBUG = 'false'
LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'error'
DB_CONNECTION = 'mysql'
SESSION_DRIVER = 'database'
CACHE_DRIVER = 'database'
QUEUE_CONNECTION = 'database'