[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -lc 'set -e; DB_FILE=${DB_DATABASE:-/app/database/banco.sqlite}; mkdir -p \"$(dirname \"$DB_FILE\")\"; [ -f \"$DB_FILE\" ] || touch \"$DB_FILE\"; php artisan config:clear && php artisan migrate --force && php artisan route:cache && php artisan view:cache && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT'"