[phases.setup]
nixPkgs = ['php82', 'nodejs_18']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install --production',
    'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'