# name: Deploy Laravel Application

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18'
#         cache: 'npm'
    
#     - name: Install dependencies
#       run: npm ci
    
#     - name: Build assets
#       run: npm run build
    
#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v4
#       with:
#         name: build-files
#         path: public/build/

#   deploy:
#     runs-on: ubuntu-latest
#     needs: [build]
#     if: github.ref == 'refs/heads/main'
    
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Download build artifacts
#       uses: actions/download-artifact@v4
#       with:
#         name: build-files
#         path: public/build/
    
#     - name: Deploy to production
#       run: |
#         echo "Deploying to production server..."
#         # Adicione aqui os comandos específicos do seu servidor
#         # Exemplo: rsync, scp, ou deploy via SSH
name: Deploy to KingHost

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql
        coverage: none
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Composer dependencies
      run: composer install --optimize-autoloader --no-dev
      
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
      
    - name: Store artifact for distribution
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ${{ github.sha }}.tar.gz
        
    - name: Deploy to KingHost
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/projetoerpagricola
          wget https://github.com/${{ github.repository }}/releases/download/latest/${{ github.sha }}.tar.gz
          tar -xzf ${{ github.sha }}.tar.gz -C laravel/
          cd laravel
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize